# Generated by Django 4.1.13 on 2023-11-25 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=30, verbose_name='Customer Name')),
                ('customerEmail', models.CharField(max_length=40, verbose_name='Email ID')),
                ('customerPhone', models.IntegerField(verbose_name='Phone No')),
                ('customerPassword', models.CharField(max_length=14, verbose_name='Password')),
                ('customerDateOfBirth', models.DateField(null=True)),
                ('customerGender', models.CharField(max_length=6, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='DealerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealerName', models.CharField(max_length=30, verbose_name='Customer Name')),
                ('dealerAddress', models.CharField(max_length=100, verbose_name='Address')),
                ('dealerPhone', models.IntegerField(verbose_name='Phone No')),
                ('dealerAnotherPhone', models.IntegerField(default=None, null=True, verbose_name='Another Phone No')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokiyoOrderId', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Tokiyo Order Id')),
                ('deliverAddressInOrder', models.CharField(max_length=140, verbose_name='Delivery Address')),
                ('deliveryNumberInOrder', models.IntegerField(verbose_name='Delivery Phone No')),
                ('totalItemCostInOrder', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total cost')),
                ('discountInOrder', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Discount')),
                ('totalAmountPaidInOrder', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Total amount paid')),
                ('orderPlacedTimeDate', models.CharField(default=None, max_length=30, verbose_name='order Placed Time & Date')),
                ('orderPlacedDate', models.DateField(default=django.utils.timezone.now, null=True)),
                ('orderDeliveredDate', models.DateField(default=django.utils.timezone.now, null=True)),
                ('orderStatusInOrder', models.CharField(default='N', max_length=1, verbose_name='Delivery Status')),
                ('customerIdInOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.customerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImage', models.ImageField(upload_to='productImages/', verbose_name='Product Image')),
                ('productName', models.CharField(max_length=30, verbose_name='Product Name')),
                ('productCategory', models.CharField(choices=[('Action Figure', 'Action Figure'), ('Accessories', 'Accessories'), ('Katana', 'Katana'), ('Posters', 'Posters')], max_length=30, verbose_name='Product Category')),
                ('productSubCategory', models.CharField(choices=[('NARUTO', 'NARUTO'), ('ONE PIECE', 'ONE PIECE'), ('DEMON SLAYER', 'DEMON SLAYER'), ('ONE PUNCH MAN', 'ONE PUNCH MAN'), ('ATTACK ON TITAN', 'ATTACK ON TITAN'), ('TOKYO REVENGER', 'TOKYO REVENGER'), ('JUJUTSU KAISEN', 'JUJUTSU KAISEN'), ('DEATH NOTE', 'DEATH NOTE')], max_length=30, verbose_name='Product Sub Category')),
                ('productCharacterCategory', models.CharField(choices=[('NARUTO', [('Naruto', 'Naruto'), ('Kakashi', 'Kakashi'), ('Sasuke', 'Sasuke'), ('Sakura', 'Sakura'), ('Jiraiya', 'Jiraiya'), ('Akatsuki', 'Akatsuki')]), ('ONE PIECE', [('STRAW HAT LUFFY', 'STRAW HAT LUFFY'), ('VINSMOKE SANJI', 'VINSMOKE SANJI'), ('RORONOA ZORO', 'RORONOA ZORO'), ('NAMI', 'NAMI'), ('CHOPPER', 'CHOPPER'), ('BROOK', 'BROOK'), ('USOPP', 'USOPP'), ('FRANKY', 'FRANKY'), ('JIMBE', 'JIMBE')]), ('DEMON SLAYER', [('TANJIRO KAMADO', 'TANJIRO KAMADO'), ('INOSUKE HASHIBIRA', 'INOSUKE HASHIBIRA'), ('ZENITSU AGATSUMA', 'ZENITSU AGATSUMA'), ('NEZUKO KAMADO', 'NEZUKO KAMADO'), ('GIYU TOMIOKA', 'GIYU TOMIOKA'), ('MUZAN KIBUTSUJI', 'MUZAN KIBUTSUJI'), ('RENGOKU', 'RENGOKU'), ('GENYA SHINAZUGAWA', 'GENYA SHINAZUGAWA'), ('MUICHIRO TOKITO', 'MUICHIRO TOKITO')]), ('ONE PUNCH MAN', [('SAITAMA', 'SAITAMA'), ('MUMEN RAIDER', 'MUMEN RAIDER'), ('GENOS', 'GENOS'), ('SILVER FANG', 'SILVER FANG'), ('TORNADO OF TERROR', 'TORNADO OF TERROR'), ('CHILD EMPEROR', 'CHILD EMPEROR'), ('FUBUKI', 'FUBUKI'), ('AMAI MASK', 'AMAI MASK')]), ('ATTACK ON TITAN', [('EREN YEAGER', 'EREN YEAGER'), ('ERWIN SMITH', 'ERWIN SMITH'), ('LEVI ACKERMAN', 'LEVI ACKERMAN'), ('JEAN KIRSTEIN', 'JEAN KIRSTEIN')]), ('TOKYO REVENGER', [('Draken', 'Draken'), ('Takemichi Hanagaki', 'Takemichi Hanagaki'), ('Takashi Mitsuya', 'Takashi Mitsuya')]), ('JUJUTSU KAISEN', [('Yuji Itadori', 'Yuji Itadori'), ('Satoru Gojo', 'Satoru Gojo')]), ('DEATH NOTE', [('Ryuk', 'Ryuk'), ('Light Yagami', 'Light Yagami'), ('Teru Mikami', 'Teru Mikami')])], max_length=30, verbose_name='Product Character Category')),
                ('productBuyingPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Product Buying Price')),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Product Price')),
                ('productSellingPrice', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Product Selling Price')),
                ('productQuantity', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Quantity')),
                ('productDescription', models.TextField(verbose_name='Product Description')),
                ('productDealerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.dealerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='productImages/', verbose_name='Product Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TokiyoApp.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQuantityInODP', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Quantity')),
                ('productPrizingInODP', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sum of products')),
                ('customerIdInODP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.customerdetail')),
                ('orderDetailSId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.orderdetail')),
                ('productIdInODP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.productdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddressDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutomerHouseNo', models.CharField(max_length=10, verbose_name='Customer House No')),
                ('cutomerAddressLine1', models.CharField(max_length=30, verbose_name='Address Line 1')),
                ('cutomerAddressLine2', models.CharField(max_length=30, verbose_name='Address Line 2')),
                ('customerCity', models.CharField(max_length=20, verbose_name='City')),
                ('customerState', models.CharField(max_length=20, verbose_name='State')),
                ('customerPinCode', models.IntegerField(verbose_name='Pin Code')),
                ('customerDeliveryNumber', models.IntegerField(verbose_name='Delivery Phone No')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.customerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='CartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQuantityInCart', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Quantity')),
                ('productPrizingInCart', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Sum of products')),
                ('customerIdInCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.customerdetail')),
                ('productIdInCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TokiyoApp.productdetail')),
            ],
        ),
    ]
