# Generated by Django 4.1.13 on 2023-11-25 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokiyoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='productDealerId',
        ),
        migrations.DeleteModel(
            name='DealerDetail',
        ),
    ]
