# Generated by Django 4.1.13 on 2023-11-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokiyoApp', '0003_remove_productdetail_productbuyingprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='productCharacterCategory',
            field=models.CharField(choices=[('NARUTO', [('Naruto', 'Naruto'), ('Kakashi', 'Kakashi'), ('Sasuke', 'Sasuke'), ('Sakura', 'Sakura'), ('Jiraiya', 'Jiraiya'), ('Akatsuki', 'Akatsuki'), ('Iruka Sensei', 'Iruka Sensei'), ('Pain', 'pain'), ('Itachi Uchiha', 'Itachi Uchiha'), ('Gara', 'Gara'), ('Tsunade', 'Tsunade'), ('Zetsu', 'Zetsu'), ('Mighty Guy', 'Mighty Guy')]), ('ONE PIECE', [('STRAW HAT LUFFY', 'STRAW HAT LUFFY'), ('VINSMOKE SANJI', 'VINSMOKE SANJI'), ('RORONOA ZORO', 'RORONOA ZORO'), ('NAMI', 'NAMI'), ('CHOPPER', 'CHOPPER'), ('Nico Robin', 'Nico Robin'), ('BROOK', 'BROOK'), ('USOPP', 'USOPP'), ('FRANKY', 'FRANKY'), ('JIMBE', 'JIMBE'), ('White Beard', 'White Beard'), ('Donquixote Rosinante', 'Donquixote Rosinante'), ('Donquixote Dofamingo', 'Donquixote Dofamingo'), ('Boa Hancock', 'Boa Hancock'), ('Dracule Mihawk', 'Dracule Mihawk'), ('Gol D Roger', 'Gol D Roger'), ('Shanks', 'Shanks'), ('Garp D Luffy', 'Garp D Luffy'), ('Trafalgar D Law', 'Trafalgar D Law'), ('Rebecca', 'Rebecca'), ('Big Mom', 'Big Mom'), ('Ace D Roger', 'Ace D Roger')]), ('DEMON SLAYER', [('TANJIRO KAMADO', 'TANJIRO KAMADO'), ('INOSUKE HASHIBIRA', 'INOSUKE HASHIBIRA'), ('ZENITSU AGATSUMA', 'ZENITSU AGATSUMA'), ('NEZUKO KAMADO', 'NEZUKO KAMADO'), ('GIYU TOMIOKA', 'GIYU TOMIOKA'), ('MUZAN KIBUTSUJI', 'MUZAN KIBUTSUJI'), ('RENGOKU', 'RENGOKU'), ('GENYA SHINAZUGAWA', 'GENYA SHINAZUGAWA'), ('MUICHIRO TOKITO', 'MUICHIRO TOKITO'), ('Tengen Uzui', 'Tengen Uzui'), ('Mitsuri Kanroji', 'Mitsuri Kanroji')]), ('ONE PUNCH MAN', [('SAITAMA', 'SAITAMA'), ('MUMEN RAIDER', 'MUMEN RAIDER'), ('GENOS', 'GENOS'), ('SILVER FANG', 'SILVER FANG'), ('TORNADO OF TERROR', 'TORNADO OF TERROR'), ('CHILD EMPEROR', 'CHILD EMPEROR'), ('FUBUKI', 'FUBUKI'), ('AMAI MASK', 'AMAI MASK')]), ('ATTACK ON TITAN', [('EREN YEAGER', 'EREN YEAGER'), ('ERWIN SMITH', 'ERWIN SMITH'), ('LEVI ACKERMAN', 'LEVI ACKERMAN'), ('JEAN KIRSTEIN', 'JEAN KIRSTEIN')]), ('TOKYO REVENGER', [('Draken', 'Draken'), ('Takemichi Hanagaki', 'Takemichi Hanagaki'), ('Takashi Mitsuya', 'Takashi Mitsuya')]), ('JUJUTSU KAISEN', [('Yuji Itadori', 'Yuji Itadori'), ('Satoru Gojo', 'Satoru Gojo'), ('Nanami', 'Nanami'), ('Sukuna', 'Sukuna')]), ('DEATH NOTE', [('Ryuk', 'Ryuk'), ('Light Yagami', 'Light Yagami'), ('Teru Mikami', 'Teru Mikami')]), ('GOKU', [('GOKU', 'GOKU')])], max_length=30, verbose_name='Product Character Category'),
        ),
    ]
