# Generated by Django 4.1.13 on 2023-11-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TokiyoApp', '0004_alter_productdetail_productcharactercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='productCategory',
            field=models.CharField(choices=[('Action Figure', 'Action Figure'), ('Accessories', 'Accessories'), ('Katana', 'Katana'), ('Posters', 'Posters')], max_length=40, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productCharacterCategory',
            field=models.CharField(choices=[('NARUTO', [('Naruto', 'Naruto'), ('Kakashi', 'Kakashi'), ('Sasuke', 'Sasuke'), ('Sakura', 'Sakura'), ('Jiraiya', 'Jiraiya'), ('Akatsuki', 'Akatsuki'), ('Iruka Sensei', 'Iruka Sensei'), ('Pain', 'pain'), ('Itachi Uchiha', 'Itachi Uchiha'), ('Gara', 'Gara'), ('Tsunade', 'Tsunade'), ('Zetsu', 'Zetsu'), ('Mighty Guy', 'Mighty Guy'), ('Madara Uchiha', 'Madara Uchiha')]), ('ONE PIECE', [('STRAW HAT LUFFY', 'STRAW HAT LUFFY'), ('VINSMOKE SANJI', 'VINSMOKE SANJI'), ('RORONOA ZORO', 'RORONOA ZORO'), ('NAMI', 'NAMI'), ('CHOPPER', 'CHOPPER'), ('Nico Robin', 'Nico Robin'), ('Brook', 'Brook'), ('God Usopp', 'God Usopp'), ('Franky', 'Franky'), ('Jimbe', 'Jimbe'), ('White Beard', 'White Beard'), ('Donquixote Rosinante', 'Donquixote Rosinante'), ('Donquixote Dofamingo', 'Donquixote Dofamingo'), ('Boa Hancock', 'Boa Hancock'), ('Dracule Mihawk', 'Dracule Mihawk'), ('Gol D Roger', 'Gol D Roger'), ('Shanks', 'Shanks'), ('Garp D Luffy', 'Garp D Luffy'), ('Trafalgar D Law', 'Trafalgar D Law'), ('Rebecca', 'Rebecca'), ('Big Mom', 'Big Mom'), ('Portgas D Ace', 'Portgas D Ace')]), ('DEMON SLAYER', [('TANJIRO KAMADO', 'TANJIRO KAMADO'), ('INOSUKE HASHIBIRA', 'INOSUKE HASHIBIRA'), ('ZENITSU AGATSUMA', 'ZENITSU AGATSUMA'), ('NEZUKO KAMADO', 'NEZUKO KAMADO'), ('GIYU TOMIOKA', 'GIYU TOMIOKA'), ('MUZAN KIBUTSUJI', 'MUZAN KIBUTSUJI'), ('RENGOKU', 'RENGOKU'), ('GENYA SHINAZUGAWA', 'GENYA SHINAZUGAWA'), ('MUICHIRO TOKITO', 'MUICHIRO TOKITO'), ('Tengen Uzui', 'Tengen Uzui'), ('Mitsuri Kanroji', 'Mitsuri Kanroji')]), ('ONE PUNCH MAN', [('SAITAMA', 'SAITAMA'), ('MUMEN RAIDER', 'MUMEN RAIDER'), ('GENOS', 'GENOS'), ('SILVER FANG', 'SILVER FANG'), ('TORNADO OF TERROR', 'TORNADO OF TERROR'), ('CHILD EMPEROR', 'CHILD EMPEROR'), ('FUBUKI', 'FUBUKI'), ('AMAI MASK', 'AMAI MASK')]), ('ATTACK ON TITAN', [('EREN YEAGER', 'EREN YEAGER'), ('ERWIN SMITH', 'ERWIN SMITH'), ('LEVI ACKERMAN', 'LEVI ACKERMAN'), ('JEAN KIRSTEIN', 'JEAN KIRSTEIN')]), ('TOKYO REVENGER', [('Draken', 'Draken'), ('Takemichi Hanagaki', 'Takemichi Hanagaki'), ('Takashi Mitsuya', 'Takashi Mitsuya')]), ('JUJUTSU KAISEN', [('Yuji Itadori', 'Yuji Itadori'), ('Satoru Gojo', 'Satoru Gojo'), ('Nanami', 'Nanami'), ('Sukuna', 'Sukuna')]), ('DEATH NOTE', [('Ryuk', 'Ryuk'), ('Light Yagami', 'Light Yagami'), ('Teru Mikami', 'Teru Mikami')]), ('GOKU', [('GOKU', 'GOKU')])], max_length=40, verbose_name='Product Character Category'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productName',
            field=models.CharField(max_length=50, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='productSubCategory',
            field=models.CharField(choices=[('NARUTO', 'NARUTO'), ('ONE PIECE', 'ONE PIECE'), ('DEMON SLAYER', 'DEMON SLAYER'), ('ONE PUNCH MAN', 'ONE PUNCH MAN'), ('ATTACK ON TITAN', 'ATTACK ON TITAN'), ('TOKYO REVENGER', 'TOKYO REVENGER'), ('JUJUTSU KAISEN', 'JUJUTSU KAISEN'), ('DEATH NOTE', 'DEATH NOTE'), ('GOKU', 'GOKU')], max_length=40, verbose_name='Product Sub Category'),
        ),
    ]
